### PR TITLE
[Feature] Merge multiple segments / skip adjacent segments with threshold parameter

### PR DESCRIPTION
**Pull request by stephen304**
I got tired of waiting for 2 skips for ad reads before intro segments, so I made this and use 1.0 as a threshold and it seems to work great!

Note: This would change the default behavior to skipping multiple overlapping segments in 1 skip, I think that's a nice improvement if the code seems safe

### CODE REVIEW

**Comment by stephen304** [comment]
I also adjusted the minimum segment length check to apply after merging segments and added some comments

**Comment by erdnaxeli** [comment]
Seems great, I'll look at it this afternoon. Do you have an example of such a video with two adjacent segments? I never saw that :thinking:

**Comment by stephen304** [comment]
Linus tech tips is a good example, since nearly all of their videos have a sponsor right before the intro: https://www.youtube.com/watch?v=eWSQ7Cj_n5M

**Comment by erdnaxeli** [comment]
That's super smooth, thanks!

**Pull request merged**
